### ISSUE TITLE
Is PURE really implied by LTABLE?

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/ZIL-Reference-Guide#2]
On pages 107 and 169, the manual states that "The flags LENGTH and PURE are implied in LTABLE , PTABLE or PLTABLE." Is that really correct? The following program:

```zil
<GLOBAL TBL <LTABLE 1 2 3 4>>

<ROUTINE GO ()
	 <TELL "Element 3 of TBL was " N <GET ,TBL 3> CR>
	 <PUT ,TBL 3 42>
	 <TELL "Now it is " N <GET ,TBL 3> CR>>
```

prints

```
Element 3 of TBL was 3
Now it is 42
```

If the table was really in static memory, I wouldn't be able to change it. Changing the table definition to

```zil
<GLOBAL TBL <LTABLE (PURE) 1 2 3 4>>
```

causes Frotz to crash with a "Store out of dynamic memory" error, as expected. I haven't tried the other table types.

**Comment by heasm66** [comment]
I've made a note of this in the document (the original is at Google Docs) and I'm gonna examine this. I don't really remember why I wrote it as I did. The document is probably full of this and I'm happy do give you access to it so you can comment directly in the document if you want.

**Comment by heasm66** [comment]
I think I mean that the flag LENGTH is implied in LTABLE and PURE is implied in a PTABLE and PLTABLE both have LENGTH and PURE.

    <LTABLE (PURE) 1 2 3> = <PTABLE (LENGTH) 1 2 3> = <TABLE (PURE LENGTH) 1 2 3> = <PLTABLE 1 2 3>

I have to check this and then clarify that sentence.

**Comment by eriktorbjorn** [comment]
> I'm happy do give you access to it so you can comment directly in the document if you want.

Unless it's inconvenient for you, I'm fine with using the GitHub issue tracker. I'm not proofreading the manual, it was just something that stood out to me while I was looking for information on tables.

**Comment by heasm66** [comment]
No inconvenience. It's perfectly fine to report bugs here.

**Comment by heasm66** [comment]
I changed the text to "The flag LENGTH is implied in LTABLE and PLTABLE. The flag PURE is implied in PTABLE and PLTABLE." is this clearer? (I will shortly publish a new PDF, 0.43) with this and some other small changes.)
