### ISSUE TITLE
Is the description of IGRTR? correct?

### ISSUE THREAD

**Issue by eriktorbjorn** [heasm66/ZIL-Reference-Guide#4]
The description of `IGRTR?` states that:

> Predicate. Increase variable (signed) name with 1and returns true if variable name is lower than value , otherwise returns false.

The original specification says the opposite:

> Increments the value of var by one and succeeds if the new value is greater than int.

Either way, there should be a space in "1and".

**Comment by heasm66** [comment]
You are correct. Copy and paste from `DLESS?`, which had the same issue with "1and".

Thanks!
